import React, { useEffect, useState } from 'react';
import { callGeminiAPI } from '../gemini';
import { loadData, saveData } from '../utils/storage';

const Coach = ({ footprint }) => {
  const [plan, setPlan] = useState(loadData('coachPlan') || null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // optionally refresh weekly if outdated
  }, []);

  const buildPrompt = (fp) => `
You are a friendly sustainability coach for a user in Bengaluru, India.
Their weekly footprint percentages are:
Consumption: ${fp.consumption}%
Travel: ${fp.travel}%
Digital: ${fp.digital}%
Finance: ${fp.finance}%

Give a short encouraging 3-point weekly action plan to reduce footprint.
Format with bolded headings (e.g., Food Tip: ...) and one sentence each.
Also add one optional quick daily micro-challenge at the end.
This will be output in an app give only in plain text not MD no * don't make it look like gemini.
`;
  const askCoach = async () => {
    setLoading(true);
    const prompt = buildPrompt(footprint);
    const res = await callGeminiAPI(prompt);
    setLoading(false);
    if (res) {
      const payload = { text: res, at: new Date().toISOString() };
      setPlan(payload);
      saveData('coachPlan', payload);
    } else {
      alert('Could not reach AI Coach. Try again later.');
    }
  };

  return (
    <>
      <header className="mb-4">
        <h1 className="text-3xl font-bold">AI Sustainability Coach</h1>
        <p className="text-gray-500">Personalized weekly actions generated by your coach.</p>
      </header>

      <div className="bg-white p-4 rounded-2xl shadow-md mb-4">
        <p className="text-sm text-gray-600 mb-2">Your current weekly snapshot:</p>
        <div className="grid grid-cols-2 gap-2 text-sm">
          <div>Consumption: <b>{footprint.consumption}%</b></div>
          <div>Travel: <b>{footprint.travel}%</b></div>
          <div>Digital: <b>{footprint.digital}%</b></div>
          <div>Finance: <b>{footprint.finance}%</b></div>
        </div>
        <div className="mt-4 flex gap-2">
          <button onClick={askCoach} className="bg-indigo-600 text-white px-4 py-2 rounded-full">Ask Coach</button>
          <button onClick={() => { setPlan(null); saveData('coachPlan', null); }} className="bg-gray-100 px-4 py-2 rounded-full">Clear</button>
        </div>
      </div>

      <div className="bg-white p-4 rounded-2xl shadow-md">
        <h3 className="font-bold mb-2">Latest Plan</h3>
        {loading && <p className="text-sm text-gray-500">Generating plan…</p>}
        {plan ? (
          <div className="text-sm" style={{ whiteSpace: 'pre-wrap' }}>{plan.text}</div>
        ) : (
          <p className="text-sm text-gray-500">No plan yet — tap “Ask Coach”.</p>
        )}
      </div>
    </>
  );
};

export default Coach;

